name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Push Build Condition
        if: github.event_name == 'push'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Latest commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" != *"[build]"* && "$COMMIT_MSG" != *"[build-apk]"* ]]; then
            echo "::notice::Skipping build because commit message does not contain [build] or [build-apk]."
            echo "BUILD_REQUIRED=false" >> $GITHUB_ENV
          else
            echo "BUILD_REQUIRED=true" >> $GITHUB_ENV
          fi

      - name: Set Build Flag for Workflow Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "BUILD_REQUIRED=true" >> $GITHUB_ENV

      - name: Set up JDK 17
        if: env.BUILD_REQUIRED == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        if: env.BUILD_REQUIRED == 'true'
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper
        if: env.BUILD_REQUIRED == 'true'
        run: gradle wrapper

      - name: Build Debug APK
        if: env.BUILD_REQUIRED == 'true'
        run: ./gradlew assembleDebug

      - name: Upload APK
        if: env.BUILD_REQUIRED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

